//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticosCerriDeposito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public sbyte idtipo { get; set; }
        public string codigocerri { get; set; }
        public double stockminimo { get; set; }
        public sbyte eliminado { get; set; }
    }
}
