//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlasticosCerriDeposito.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlasticosDBContext : DbContext
    {
        public PlasticosDBContext()
            : base("name=PlasticosDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulos> articulos { get; set; }
        public virtual DbSet<tipoproductos> tipoproductos { get; set; }
        public virtual DbSet<depositos> depositos { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<posiciones> posiciones { get; set; }
        public virtual DbSet<ingresostock> ingresostock { get; set; }
        public virtual DbSet<ingresostockd> ingresostockd { get; set; }
    }
}
